#80表示注册到consul服务器的支付服务提供者端口号
server:
  port: 80

#服务别名----注册consule到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.193.121
      port: 8500
      discovery:
        hostname: ${spring.application.name}
        heartbeat:
          enabled: true